### PR TITLE
Fix: use std logging in TestMain instead of glog to prevent verbose l…

### PR DESCRIPTION
**Pull request by DGuhr**
…og output when running go test

### PR Template:

* [x] Are the agreed upon acceptance criteria fulfilled? (no ticket, just a small go-by fix)

* [ ] Was the 4-eye-principle applied? (async PR review, pairing, ensembling)

* [x] Do your changes have passing automated tests and sufficient observability? (not apply)

* [x] Are the work steps you introduced repeatable by others, either through automation or documentation?
  * [ ] If automation is possible but not done due to other constraints, a ticket to the tech debt sprint is added
  * [ ] An SOP (Standard Operating Procedure) was created

* [ ] The Changes were automatically built, tested, and  - if needed, behind a feature flag - deployed to our production environment. (**Please check this when the new deployment is done and you could verify it.**)

* [x] Are the agreed upon coding/architectural practices applied? (this basically introduces a new coding practice, **don't use glog in TestMain**)

* [x] Are security needs fullfilled? (e.g. no internal URL)

* [x] Is the corresponding Ticket in the right state? (should be on "review" now, put to done when this change made it to production) (can create if wanted)

* [x] For changes to the public API / code dependencies: Was the whole team (or a sufficient amount of ppl) able to review?

### CODE REVIEW

**Comment by DGuhr** [comment]
Before: 
Screenshot 2023-04-14 at 18 42 00

After:
Screenshot 2023-04-14 at 18 41 35

To reproduce: don't have docker running, run go test ./... - I prefer the small logging.

This PR opens up another small can of worms:
- given the pr makes it, it will trigger a re-deploy. Question is: Is that okay? Or should we not trigger a re-deploy if we "only" change sth at the test setup? I am not quite sure this would be possible if the tests are not in one folder (that we could exclude using e.g. [paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths), though scanning the docs it should be possible to not trigger the deployment step by using a pattern such as `*_test`

**Comment by merlante** [comment]
Is there something we could do along the lines of https://github.com/RedHatInsights/authz/blob/main/cmd/main.go#L18-L21 for tests as well? Or a more global solution? 

If we just change from "glog" to "log" in just this one place, someone will eventually think it's a mistake and try to change it back.

**Comment by merlante** [comment]
> Before: Screenshot 2023-04-14 at 18 42 00
> 
> After: Screenshot 2023-04-14 at 18 41 35
> 
> To reproduce: don't have docker running, run go test ./... - I prefer the small logging.
> 
> This PR opens up another small can of worms:
> 
> * given the pr makes it, it will trigger a re-deploy. Question is: Is that okay? Or should we not trigger a re-deploy if we "only" change sth at the test setup? I am not quite sure this would be possible if the tests are not in one folder (that we could exclude using e.g. [paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths), though scanning the docs it should be possible to not trigger the deployment step by using a pattern such as `*_test`

Redeploying might not be desirable in these circumstances, but it feels like it would be easier to keep the existing "all or nothing" flow than to test this kind of logic. Also, what are we losing by leaving the status quo? More images will be in quay.io, but that I guess that will be fine.

**Comment by DGuhr** [comment]
totally happy to leave it as is, hence the "is that okay?"

**Comment by DGuhr** [comment]
closed, no engagement.

**Pull request closed without merging**
