### PR TITLE
Spicedb integration tests

### PR DESCRIPTION
**Pull request by wscalf**
Adds a range of integration tests on the SpiceDB repository using dockertest

### CODE REVIEW

**Review by akoserwal — APPROVED** [review]
LGTM

**Comment by merlante** [comment]
LGTM

**Comment by Rajagopalan-Ranganathan** [comment]
LGTM

**Review by Rajagopalan-Ranganathan — APPROVED** [review]

**Review by DGuhr — APPROVED** [review]
LGTM - still not sure about the strong consistency need in the "real" application, but I'm concerned about performance, and first rule of performance optimization is: "don't do it until it's really needed", so I stick with that having no data. ;)

**Pull request merged**
