### PR TITLE
Pass endpoint configuration via builders

### PR DESCRIPTION
**Pull request by wscalf**
### PR Template:

* [x] Are the agreed upon acceptance criteria fulfilled?

* [x] Was the 4-eye-principle applied? (async PR review, pairing, ensembling)

* [x] Do your changes have passing automated tests and sufficient observability?

* [x] Are the work steps you introduced repeatable by others, either through automation or documentation?
  * [ ] If automation is possible but not done due to other constraints, a ticket to the tech debt sprint is added
  * [ ] An SOP (Standard Operating Procedure) was created

* [x] The Changes were automatically built, tested, and  - if needed, behind a feature flag - deployed to our production environment. (**Please check this when the new deployment is done and you could verify it.**)

* [x] Are the agreed upon coding/architectural practices applied?

* [x] Are security needs fullfilled? (e.g. no internal URL)

* [x] Is the corresponding Ticket in the right state? (should be on "review" now, put to done when this change made it to production)

* [x] For changes to the public API / code dependencies: Was the whole team (or a sufficient amount of ppl) able to review?

### CODE REVIEW

**Comment by DGuhr** [comment]
@wscalf I'd prefer the usage of the [config structs](https://github.com/RedHatInsights/authz/pull/86/files#diff-2f0dafa7d34db4931825737810ccffb696e08148204312dd50891bda3dd6a614L53-L63) (maybe extended with structs for the repos) over excessive function parameters (as this PR introduces, and which may grow even furrther in the future). 

We can change that later, though, your decision. PR has a check from my side.

Sidenote: I still think it might be good to not rely on flags, but a config file (mostly for bash parsing reasons, but also it allows us to easier add new config without altering with the services "public interface" (aka CLI client)). 
I used it already in here: https://github.com/RedHatInsights/authz/commit/c69c44f60fddd4301228b61b091b4c3adb493a62 but removed it to make the architecture PR not change the behaviour of the system (there it was only one flag, --config). Something for later and an arch discussion, though :)

**Review by DGuhr — APPROVED** [review]

**Review by akoserwal — APPROVED** [review]

**Comment by Rajagopalan-Ranganathan** [comment]
+1 to @DGuhr comments on usage of config structs - that can be done in a subsequent JIRA/PR as needed.
Scanning the code , not your changes in the PR, we really need to start using meaningful variable names, i see a lot of single alphabets used as a variable name.

**Review by Rajagopalan-Ranganathan — APPROVED** [review]

**Comment by wscalf** [comment]
Updated to use the config structs- I think that makes a _lot_ more sense tbh- the signatures are cleaner, and it doesn't require app.go to guess what info the builders will need- it can just pass a pointer to all of it.

Changes made and pushed.

**Comment by Rajagopalan-Ranganathan** [comment]
> Updated to use the config structs- I think that makes a _lot_ more sense tbh- the signatures are cleaner, and it doesn't require app.go to guess what info the builders will need- it can just pass a pointer to all of it.
> 
> Changes made and pushed.

Perfect! LGTM

**Pull request merged**
